FROM eclipse-temurin:17-jdk-ubi9-minimal
RUN mkdir /opt/app
COPY target/micro2-0.0.1-SNAPSHOT.jar /opt/app/micro2-0.0.1-SNAPSHOT.jar
COPY src/main/resources/application-docker.yml /opt/app/application.yml
CMD ["java", "-jar", "/opt/app/micro2-0.0.1-SNAPSHOT.jar", "--spring.config.location=file:/opt/app/application.yml"]